import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { baseDir, listInstalledPackages, type PackageType } from "./packages";

/**
 * Themes and plugins are imported statically (the bundler has to see their code), so a package
 * installed at runtime becomes known to the app through a generated file that registers every
 * marketplace-installed folder. `themes/registry.ts` and `plugins/registry.ts` spread it in.
 * In `next dev` the file change is picked up on the next request; a production build needs a
 * rebuild (`next build`) before the new code is served.
 */

const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export function generatedFile(type: PackageType) {
  return path.join(baseDir(type), "installed.generated.ts");
}

export function renderGenerated(type: PackageType, slugs: string[]): string {
  const safe = slugs.filter((s) => SLUG.test(s)).sort();
  const manifestFile = type === "theme" ? "theme.json" : "plugin.json";
  const moduleType = type === "theme" ? 'import type { ThemeModule } from "@/lib/theme/types";\nimport type { ThemeManifest } from "@/lib/theme/manifest";' : 'import type { PluginManifest } from "@/lib/plugins/manifest";\nimport type { PluginRegister } from "@/lib/plugins/api";';
  const Manifest = type === "theme" ? "ThemeManifest" : "PluginManifest";
  const Loaded = type === "theme" ? "ThemeModule" : "PluginRegister";
  const entryModule = type === "theme" ? "" : "/register";
  return `// AUTO-GENERATED by the marketplace installer (lib/marketplace/generate.ts). Do not edit by hand.
// Lists the ${type}s installed from a registry; bundled ${type}s are listed in ./registry.ts.
${moduleType}
${safe.map((s, i) => `import m${i} from "./${s}/${manifestFile}";`).join("\n")}

export const INSTALLED: Record<string, { manifest: ${Manifest}; load: () => Promise<${Loaded}> }> = {
${safe.map((s, i) => `  "${s}": {\n    manifest: m${i} as ${Manifest},\n    load: async () => (await import("./${s}${entryModule}")).default,\n  },`).join("\n")}
};
`;
}

/** Rewrite the generated file from the folders on disk. Only touches the file when it changed. */
export function regenerate(type: PackageType): boolean {
  const next = renderGenerated(type, listInstalledPackages(type).map((m) => m.slug));
  const file = generatedFile(type);
  let current = "";
  try {
    current = readFileSync(file, "utf8");
  } catch {
    // first time
  }
  if (current === next) return false;
  writeFileSync(file, next);
  return true;
}
