// AUTO-GENERATED by the marketplace installer (lib/marketplace/generate.ts). Do not edit by hand.
// Lists the plugins installed from a registry; bundled plugins are listed in ./registry.ts.
import type { PluginManifest } from "@/lib/plugins/manifest";
import type { PluginRegister } from "@/lib/plugins/api";


export const INSTALLED: Record<string, { manifest: PluginManifest; load: () => Promise<PluginRegister> }> = {

};
