// AUTO-GENERATED by the marketplace installer (lib/marketplace/generate.ts). Do not edit by hand.
// Lists the themes installed from a registry; bundled themes are listed in ./registry.ts.
import type { ThemeModule } from "@/lib/theme/types";
import type { ThemeManifest } from "@/lib/theme/manifest";


export const INSTALLED: Record<string, { manifest: ThemeManifest; load: () => Promise<ThemeModule> }> = {

};
